/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        // lg: "var(--radius)",
        // md: "calc(var(--radius) - 2px)",
        // sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      translate: {
				200: '200%',
				300: '300%',
				400: '400%',
				500: '500%',
				600: '600%',
				700: '700%',
				800: '800%',
				900: '900%',


			},
      maxWidth: {
        "5-screen": "5vw",
        "10-screen": "10vw",
        "20-screen": "20vw",
        "30-screen": "30vw",
        "40-screen": "40vw",
        "50-screen": "50vw",
        "60-screen": "60vw",
        "70-screen": "70vw",
        "72-screen": "72vw",
        "80-screen": "80vw",
        "90-screen": "90vw",
        "120-screen": "120vw",
        "140-screen": "140vw",
        "150-screen": "150vw",
        "160-screen": "160vw",
        "170-screen": "170vw",
        "180-screen": "180vw",
        "190-screen": "190vw",
        "200-screen": "200vw",
        "210-screen": "210vw",
        "220-screen": "220vw",
        "230-screen": "230vw",
        "240-screen": "240vw",
        "w-screen-xs": "425px",
      },
      maxHeight: {
        "5-screen": "5vh",
        "10-screen": "10vh",
        "20-screen": "20vh",
        "30-screen": "30vh",
        "40-screen": "40vh",
        "50-screen": "50vh",
        "60-screen": "60vh",
        "70-screen": "70vh",
        "72-screen": "72vh",
        "80-screen": "80vh",
        "90-screen": "90vh",
        "120-screen": "120vh",
        "140-screen": "140vh",
        "150-screen": "150vh",
        "160-screen": "160vh",
        "170-screen": "170vh",
        "180-screen": "180vh",
        "190-screen": "190vh",
        "200-screen": "200vh",
        "210-screen": "210vh",
        "220-screen": "220vh",
        "230-screen": "230vh",
        "240-screen": "240vh",
      },
      height: {
        18: "4.5rem",
        22: "5.5rem",
        26: "6.5rem",
        112: "448px",
        "screen-20": "20vh",
        "screen-40": "40vh",
        "screen-50": "50vh",
        "screen-55": "55vh",
        "screen-60": "60vh",
        "screen-63": "63vh",
        "screen-65": "65vh",
        "screen-70": "70vh",
        "screen-72": "72vh",
        "screen-80": "80vh",
        "screen-82": "82vh",
        "screen-90": "90vh",
        "110-screen": "110vh",
        "120-screen": "120vh",
        "130-screen": "130vh",
        "140-screen": "140vh",
        "150-screen": "150vh",
      },
      width: {
        "5-screen": "5vw",
        "10-screen": "10vw",
        "20-screen": "20vw",
        "30-screen": "30vw",
        "40-screen": "40vw",
        "50-screen": "50vw",
        "60-screen": "60vw",
        "65-screen": "65vw",
        "70-screen": "70vw",
        "72-screen": "72vw",
        "80-screen": "80vw",
        "90-screen": "90vw",
        "120-screen": "120vw",
        "140-screen": "140vw",
        "150-screen": "150vw",
        "160-screen": "160vw",
        "170-screen": "170vw",
        "180-screen": "180vw",
        "190-screen": "190vw",
        "200-screen": "200vw",
        "210-screen": "210vw",
        "220-screen": "220vw",
        "230-screen": "230vw",
        "240-screen": "240vw",
        "w-screen-xs": "425px",
      },
      minHeight: {
        "50-screen": "50vh",
        "60-screen": "60vh",
        "70-screen": "70vh",
        "72-screen": "72vh",
        "80-screen": "80vh",
        "90-screen": "90vh",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};